

export const CourseDescriptionData = [
    {
        id:'1',
        img: 'assets/1.jpg',
        course_title:'apache1',
        course_sub_title: 'web programming and apache basics',
        coruse_duration:'4 hours',
        course_cost:'free',
        instructor_profile_pics: 'img src="/assets/3.jpg" alt="" className="imgHolder"',
        isntructor_name:'demo instructor',
        course_desc: 'The wordPress plugin is a part of the Masterstudy wordPress theme for the education business. Upgrading to the theme is optional but does come with...',
        course_ranking:'beginner',
        course_delivery_type:'lectures',
        course_time_per_hour:'5hours'
    },
    {
        id:'2',
        img: 'assets/2.jpg',
        course_title:'apache',
        course_sub_title: 'web programming and apache basics',
        coruse_duration:'4 hours',
        course_cost:'free',
        instructor_profile_pics: 'img src="/assets/3.jpg" alt="" className="imgHolder"',
        isntructor_name:'demo instructor',
        course_desc: 'The wordPress plugin is a part of the Masterstudy wordPress theme for the education business. Upgrading to the theme is optional but does come with...',
        course_ranking:'beginner',
        course_delivery_type:'lectures',
        course_time_per_hour:'5hours'
    },
    {
        id:'3',
        img: 'assets/3.jpg',
        course_title:'apache',
        course_sub_title: 'web programming and apache basics',
        coruse_duration:'4 hours',
        course_cost:'free',
        instructor_profile_pics: 'img src="/assets/3.jpg" alt="" className="imgHolder"',
        isntructor_name:'demo instructor',
        course_desc: 'The wordPress plugin is a part of the Masterstudy wordPress theme for the education business. Upgrading to the theme is optional but does come with...',
        course_ranking:'beginner',
        course_delivery_type:'lectures',
        course_time_per_hour:'5hours'
    },
    {
        id:'1',
        img: 'assets/4.jpg',
        course_title:'apache1',
        course_sub_title: 'web programming and apache basics',
        coruse_duration:'4 hours',
        course_cost:'free',
        instructor_profile_pics: 'img src="/assets/3.jpg" alt="" className="imgHolder"',
        isntructor_name:'demo instructor',
        course_desc: 'The wordPress plugin is a part of the Masterstudy wordPress theme for the education business. Upgrading to the theme is optional but does come with...',
        course_ranking:'beginner',
        course_delivery_type:'lectures',
        course_time_per_hour:'5hours'
    },
    {
        id:'2',
        img: 'assets/5.jpg',
        course_title:'apache',
        course_sub_title: 'web programming and apache basics',
        coruse_duration:'4 hours',
        course_cost:'free',
        instructor_profile_pics: 'img src="/assets/3.jpg" alt="" className="imgHolder"',
        isntructor_name:'demo instructor',
        course_desc: 'The wordPress plugin is a part of the Masterstudy wordPress theme for the education business. Upgrading to the theme is optional but does come with...',
        course_ranking:'beginner',
        course_delivery_type:'lectures',
        course_time_per_hour:'5hours'
    },
    {
        id:'6',
        img: 'assets/1.jpg',
        course_title:'apache',
        course_sub_title: 'web programming and apache basics',
        coruse_duration:'4 hours',
        course_cost:'free',
        instructor_profile_pics: 'img src="/assets/3.jpg" alt="" className="imgHolder"',
        isntructor_name:'demo instructor',
        course_desc: 'The wordPress plugin is a part of the Masterstudy wordPress theme for the education business. Upgrading to the theme is optional but does come with...',
        course_ranking:'beginner',
        course_delivery_type:'lectures',
        course_time_per_hour:'5hours'
    },
];
