import { moreHorixontall, Remove, Add} from '@material-ui/icons';
export const CheckboxData = [
    {
        id:1,
        header:'my category',
        iconAdd:'<Add />',
        iconRemove:'<Remove />',
        inputType:'input type = checkox',
        checkboxtype1:'art',
        checkboxtype2:'software engineering',
        checkboxtype3:'material design',
        checkboxtype4:'music',
        checkboxtype5:'photography',
    },
    {
        id:2,
        header:'your category',
        iconAdd:'<Add />',
        iconRemove:'<Remove />',
        inputType:'input type = checkox',
        checkboxtype1:'art',
        checkboxtype2:'software engineering the number two',
        checkboxtype3:'material design',
        checkboxtype4:'music',
        checkboxtype5:'photography',
    },
    {
        id:3,
        header:'category',
        iconAdd:'<Add />',
        iconRemove:'<Remove />',
        inputType:'input type = checkox',
        checkboxtype1:'art',
        checkboxtype2:'software engineering',
        checkboxtype3:'material design',
        checkboxtype4:'music',
        checkboxtype5:'photography',
    },
    {
        id:4,
        header:'category',
        iconAdd:'<Add />',
        iconRemove:'<Remove />',
        inputType:'input type = checkox',
        checkboxtype1:'art',
        checkboxtype2:'software engineering',
        checkboxtype3:'material design',
        checkboxtype4:'music',
        checkboxtype5:'photography',
    },
    {
        id:5,
        header:'category',
        iconAdd:'<Add />',
        iconRemove:'<Remove />',
        inputType:'input type = checkox',
        checkboxtype1:'art',
        checkboxtype2:'software engineering',
        checkboxtype3:'material design',
        checkboxtype4:'music',
        checkboxtype5:'photography',
    },
   
];
